# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './akumapy.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(690, 661)
        QMainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.labelForPath = QtWidgets.QLabel(self.centralwidget)
        self.labelForPath.setObjectName("labelForPath")
        self.verticalLayout_3.addWidget(self.labelForPath)
        self.filePath = QtWidgets.QLineEdit(self.centralwidget)
        self.filePath.setInputMask("")
        self.filePath.setText("")
        self.filePath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.filePath.setObjectName("filePath")
        self.verticalLayout_3.addWidget(self.filePath)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.namepath = QtWidgets.QLineEdit(self.centralwidget)
        self.namepath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.namepath.setObjectName("namepath")
        self.verticalLayout_3.addWidget(self.namepath)
        self.useNameVar = QtWidgets.QCheckBox(self.centralwidget)
        self.useNameVar.setObjectName("useNameVar")
        self.verticalLayout_3.addWidget(self.useNameVar)
        self.plainListRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.plainListRadio.setChecked(True)
        self.plainListRadio.setObjectName("plainListRadio")
        self.verticalLayout_3.addWidget(self.plainListRadio)
        self.textFileRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.textFileRadio.setObjectName("textFileRadio")
        self.verticalLayout_3.addWidget(self.textFileRadio)
        self.jsonFileRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.jsonFileRadio.setObjectName("jsonFileRadio")
        self.verticalLayout_3.addWidget(self.jsonFileRadio)
        self.checkNSFWService = QtWidgets.QCheckBox(self.centralwidget)
        self.checkNSFWService.setObjectName("checkNSFWService")
        self.verticalLayout_3.addWidget(self.checkNSFWService)
        self.saveHTML = QtWidgets.QCheckBox(self.centralwidget)
        self.saveHTML.setObjectName("saveHTML")
        self.verticalLayout_3.addWidget(self.saveHTML)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.htmlTags = QtWidgets.QLineEdit(self.centralwidget)
        self.htmlTags.setObjectName("htmlTags")
        self.verticalLayout_3.addWidget(self.htmlTags)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.pathToHTML = QtWidgets.QLineEdit(self.centralwidget)
        self.pathToHTML.setObjectName("pathToHTML")
        self.verticalLayout_3.addWidget(self.pathToHTML)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.usernameIn = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameIn.setInputMask("")
        self.usernameIn.setText("")
        self.usernameIn.setObjectName("usernameIn")
        self.verticalLayout_3.addWidget(self.usernameIn)
        self.go = QtWidgets.QPushButton(self.centralwidget)
        self.go.setObjectName("go")
        self.verticalLayout_3.addWidget(self.go)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 22))
        self.menubar.setObjectName("menubar")
        self.menuInformation = QtWidgets.QMenu(self.menubar)
        self.menuInformation.setObjectName("menuInformation")
        self.menuInsert = QtWidgets.QMenu(self.menubar)
        self.menuInsert.setObjectName("menuInsert")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)
        self.creditsTrigger = QtWidgets.QAction(QMainWindow)
        self.creditsTrigger.setObjectName("creditsTrigger")
        self.insertionTrigger = QtWidgets.QAction(QMainWindow)
        self.insertionTrigger.setObjectName("insertionTrigger")
        self.menuInformation.addAction(self.creditsTrigger)
        self.menuInsert.addAction(self.insertionTrigger)
        self.menubar.addAction(self.menuInformation.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "AkumaPy | Forensic Search"))
        self.label_4.setText(_translate("QMainWindow", "Log:"))
        self.labelForPath.setText(_translate("QMainWindow", "Path to logfile (optional)"))
        self.label_5.setText(_translate("QMainWindow", "Path to namevariation wordlist:"))
        self.useNameVar.setText(_translate("QMainWindow", "Wordlisted namevariation"))
        self.plainListRadio.setText(_translate("QMainWindow", "Simple Output"))
        self.textFileRadio.setText(_translate("QMainWindow", "To .txt file"))
        self.jsonFileRadio.setText(_translate("QMainWindow", "To .json file"))
        self.checkNSFWService.setText(_translate("QMainWindow", "NSFW"))
        self.saveHTML.setText(_translate("QMainWindow", "Save HTML Content of specific Tag"))
        self.label_3.setText(_translate("QMainWindow", "HTML Tag (Optional e.g. \"p\" or \"main\")"))
        self.label.setText(_translate("QMainWindow", "Path to HTML file (optional)"))
        self.label_2.setText(_translate("QMainWindow", "Username to hunt"))
        self.go.setText(_translate("QMainWindow", "Start the Hunt"))
        self.menuInformation.setTitle(_translate("QMainWindow", "Information"))
        self.menuInsert.setTitle(_translate("QMainWindow", "Insert"))
        self.creditsTrigger.setText(_translate("QMainWindow", "Credits"))
        self.insertionTrigger.setText(_translate("QMainWindow", "Insert new link"))
